[languages]
nodejs = "18"  

[phases]
setup = "npm ci"
build = "npm run build"
start = "npm run deploy"

[variables]
NODE_ENV = "production"
DATABASE_URL = "${postgresql://postgres:ZUQvXwqwLgcHfOXfVzEPKRzOrbJwzLJV@viaduct.proxy.rlwy.net:25045/railway}"  
