[languages]
nodejs = "18"

[phases]
setup = "npm ci --legacy-peer-deps"
build = "npm run build"
start = "npm run deploy"

[variables]
NODE_ENV = "production"
DATABASE_URL = "postgresql://postgres:yuqEwjGDpQEWJvjDZcotCXhaRVUPPEuW@roundhouse.proxy.rlwy.net:42476/railway"
